### ISSUE TITLE
Broken link (Weird Article)

### ISSUE THREAD

**Issue by darksunlight** [SeedFinding/fnseedc#8]
https://tailcall.net/blog/cracking-randomness-lcgs/ is gone, fortunately it's archived: https://web.archive.org/web/20181222235217/https://tailcall.net/blog/cracking-randomness-lcgs/

**Comment by leimath** [comment]
Thank you. I will fix it.

(Also sorry for the late response!)

**Comment by XI64** [comment]
Should be fixed in the next commit. Thanks for the heads up!

(Sorry for the late response :P )
